// AUTO-GENERATED FILE - DO NOT EDIT
// This file will be generated by ffigen
// For now, manually created bindings

import 'dart:ffi';
import 'dart:io';
import 'package:ffi/ffi.dart';

// Function signatures - must be top-level
typedef FipersInitNative = Pointer Function(
  Pointer<Utf8> path,
  Pointer<Utf8> passphrase,
  Pointer<Int32> errorCode,
);
typedef FipersInitDart = Pointer Function(
  Pointer<Utf8> path,
  Pointer<Utf8> passphrase,
  Pointer<Int32> errorCode,
);

typedef FipersPutNative = Int32 Function(
  Pointer handle,
  Pointer<Utf8> key,
  Pointer<Uint8> data,
  IntPtr dataLen,
  Pointer<Int32> errorCode,
);
typedef FipersPutDart = int Function(
  Pointer handle,
  Pointer<Utf8> key,
  Pointer<Uint8> data,
  int dataLen,
  Pointer<Int32> errorCode,
);

typedef FipersGetNative = Int32 Function(
  Pointer handle,
  Pointer<Utf8> key,
  Pointer<Pointer<Uint8>> outData,
  Pointer<UintPtr> outLen,
  Pointer<Int32> errorCode,
);
typedef FipersGetDart = int Function(
  Pointer handle,
  Pointer<Utf8> key,
  Pointer<Pointer<Uint8>> outData,
  Pointer<UintPtr> outLen,
  Pointer<Int32> errorCode,
);

typedef FipersDeleteNative = Int32 Function(
  Pointer handle,
  Pointer<Utf8> key,
  Pointer<Int32> errorCode,
);
typedef FipersDeleteDart = int Function(
  Pointer handle,
  Pointer<Utf8> key,
  Pointer<Int32> errorCode,
);

typedef FipersCloseNative = Void Function(Pointer handle);
typedef FipersCloseDart = void Function(Pointer handle);

typedef FipersFreeDataNative = Void Function(Pointer<Uint8> data);
typedef FipersFreeDataDart = void Function(Pointer<Uint8> data);

/// Native bindings for Fipers storage library
class StorageBindings {
  static DynamicLibrary? _lib;
  static StorageBindings? _instance;

  StorageBindings._();

  static StorageBindings get instance {
    _instance ??= StorageBindings._();
    return _instance!;
  }

  DynamicLibrary get library {
    if (_lib != null) return _lib!;

    if (Platform.isAndroid) {
      _lib = DynamicLibrary.open('libfipers.so');
    } else if (Platform.isIOS || Platform.isMacOS) {
      _lib = DynamicLibrary.process();
    } else if (Platform.isLinux) {
      // Try to find library relative to executable (Flutter bundle structure)
      final executablePath = Platform.resolvedExecutable;
      final executableDir = executablePath.substring(0, executablePath.lastIndexOf('/'));
      
      // Get project root (assuming test or app is running from project)
      final currentDir = Directory.current.path;
      
      // Flutter Linux apps have structure: bundle/executable and bundle/lib/libfipers.so
      // Also try project build directory for tests
      final possiblePaths = [
        '$executableDir/lib/libfipers.so', // Standard Flutter bundle structure
        '${executableDir.substring(0, executableDir.lastIndexOf('/'))}/lib/libfipers.so', // Parent dir
        '$currentDir/linux/build/libfipers.so', // Project build directory (for tests)
        '$currentDir/../linux/build/libfipers.so', // Relative to test directory
        '$currentDir/../../linux/build/libfipers.so', // Relative to test directory (nested)
        'libfipers.so', // Current directory (fallback)
        './libfipers.so', // Relative path (fallback)
      ];

      DynamicLibrary? lib;
      Exception? lastError;
      
      for (final path in possiblePaths) {
        try {
          lib = DynamicLibrary.open(path);
          break;
        } catch (e) {
          lastError = e is Exception ? e : Exception(e.toString());
          continue;
        }
      }

      if (lib == null) {
        // Log all attempted paths for debugging
        print('Failed to load libfipers.so. Executable: $executablePath');
        print('Current directory: $currentDir');
        print('Tried paths: ${possiblePaths.join(', ')}');
        throw UnsupportedError(
          'Failed to load libfipers.so. Executable: $executablePath. '
          'Current directory: $currentDir. '
          'Tried paths: ${possiblePaths.join(', ')}. '
          'Last error: $lastError',
        );
      }

      _lib = lib;
    } else if (Platform.isWindows) {
      _lib = DynamicLibrary.open('fipers.dll');
    } else {
      throw UnsupportedError('Platform not supported: ${Platform.operatingSystem}');
    }

    return _lib!;
  }

  // Function references
  late final FipersInitDart fipersInit =
      library.lookupFunction<FipersInitNative, FipersInitDart>('fipers_init');

  late final FipersPutDart fipersPut =
      library.lookupFunction<FipersPutNative, FipersPutDart>('fipers_put');

  late final FipersGetDart fipersGet =
      library.lookupFunction<FipersGetNative, FipersGetDart>('fipers_get');

  late final FipersDeleteDart fipersDelete =
      library.lookupFunction<FipersDeleteNative, FipersDeleteDart>('fipers_delete');

  late final FipersCloseDart fipersClose =
      library.lookupFunction<FipersCloseNative, FipersCloseDart>('fipers_close');

  late final FipersFreeDataDart fipersFreeData =
      library.lookupFunction<FipersFreeDataNative, FipersFreeDataDart>('fipers_free_data');
}
